[dev]
  command = "pnpm start"
  port = 3000
  autoLaunch = true
  framework = "express"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  optimize = true

[build]
  command = "pnpm install && pnpm run build"
  publish = "public"

[template]
  incoming-hooks = ["Contentful"]
  required-extensions = ["supabase"]

  [template.onboarding]
    instructions = """
    Welcome to your new Express + Supabase project!
    1. Replace the SUPABASE_URL and SUPABASE_KEY in [template.environment].
    2. Set your SESSION_SECRET to a secure random string.
    3. Run `pnpm install` and `pnpm start` to begin development.
    """

  [template.environment]
      SUPABASE_URL = "change me to your supabase url"
      SUPABASE_KEY = "change me to your supabase anon key"
      SESSION_SECRET = "change me to your express session secret"
      PORT = "3000"

  [dev]
    command = "pnpm install && pnpm run dev"
    port = 3000